Update stuff

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -130,7 +130,10 @@ jobs:
         run: |
           set -ue
           echo "Switching to release branch '${TARGET_BRANCH}'"
-          git checkout ${TARGET_BRANCH}
+          if ! git checkout ${TARGET_BRANCH}; then
+            echo "::error::Checking out release branch '${TARGET_BRANCH}' for target version '${TARGET_VERSION}' (tagged '${RELEASE_TAG}') failed. Does it exist in repo?"
+            exit 1
+          fi
 
       - name: Create VERSION information
         run: |
